title: Shellya Nur Atqiya # your name (or website title) here
logo: "/images/SNA.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Final-Year Mathematics Students
  <br>
  shellyanat@upi.edu | shellyanra08@gmail.com
  <br><br><br>
  
  <a href="https://www.linkedin.com/in/shellyanra/">View My LinkedIn Profile</a> 
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
